repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix, --select=I]
      - id: ruff-format

  - repo: local
    hooks:
      - id: uv-lock
        name: uv lock
        entry: bash -c 'uv lock && git add uv.lock'
        language: system
        pass_filenames: false
        files: pyproject.toml
